Feature/processo
SWEasabi/piano-di-qualifica pull request #11
Opened 2023-03-05 18:30 UTC by casYy

Ci sono alcuni dubbi lasciati come note nel documento. Una volta accettata questa pr chiude la issue #5

2023-03-06 15:10 UTC, pierobonluca01 requested changes

2023-03-06 15:14 UTC, pierobonluca01 commented on src-doc/contenuti/qualita-di-processo.tex
> +
Aggiunta della metrica di Accertamento della Qualità?
Quality Metrics Satisfied (QMS)

2023-03-06 15:17 UTC, casYy commented on src-doc/contenuti/qualita-di-processo.tex
non le ho messe di proposito, però le posso tranquillamente aggiungere.

2023-03-06 15:24 UTC, casYy commented on src-doc/contenuti/qualita-di-processo.tex
> +        \item \textbf{Soglia accettabile}: ≥ 8. % non saprei sulle soglie onestamente
corretto

2023-03-06 15:25 UTC, casYy commented on src-doc/contenuti/qualita-di-processo.tex
> +
ok, posso aggiungerla stasera

2023-03-15 19:28 UTC, bonni1207 approved these changes

2023-03-15 19:32 UTC, bonni1207 approved these changes

2023-03-15 19:58 UTC, pierobonluca01 approved these changes

2023-03-15 20:00 UTC, merged